name: microgalaxy_technical_paper
channels:
- conda-forge
- defaults
- bioconda
dependencies:
- jupyter
- pandas
- matplotlib
- pyzotero
- scholarly
- fake-useragent
- r-base
- r-data.table
- r-stringr
- r-rmarkdown
- r-tidytext
- r-tidyr
- r-ggplot2
- r-ggrepel
- r-ggtext
- r-ggh4x
- r-shadowtext
- r-extrafont
- r-paletteer
- r-colorspace
- r-packcircles
- r-patchwork
